// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifs.proto

package notifsproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendNotificationMessage struct {
	VacancyID            string   `protobuf:"bytes,1,opt,name=VacancyID,proto3" json:"VacancyID,omitempty"`
	TagIDs               []string `protobuf:"bytes,2,rep,name=TagIDs,proto3" json:"TagIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotificationMessage) Reset()         { *m = SendNotificationMessage{} }
func (m *SendNotificationMessage) String() string { return proto.CompactTextString(m) }
func (*SendNotificationMessage) ProtoMessage()    {}
func (*SendNotificationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_23033505e9d20bff, []int{0}
}

func (m *SendNotificationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotificationMessage.Unmarshal(m, b)
}
func (m *SendNotificationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotificationMessage.Marshal(b, m, deterministic)
}
func (m *SendNotificationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotificationMessage.Merge(m, src)
}
func (m *SendNotificationMessage) XXX_Size() int {
	return xxx_messageInfo_SendNotificationMessage.Size(m)
}
func (m *SendNotificationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotificationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotificationMessage proto.InternalMessageInfo

func (m *SendNotificationMessage) GetVacancyID() string {
	if m != nil {
		return m.VacancyID
	}
	return ""
}

func (m *SendNotificationMessage) GetTagIDs() []string {
	if m != nil {
		return m.TagIDs
	}
	return nil
}

type Bool struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_23033505e9d20bff, []int{1}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*SendNotificationMessage)(nil), "notifsproto.SendNotificationMessage")
	proto.RegisterType((*Bool)(nil), "notifsproto.Bool")
}

func init() { proto.RegisterFile("notifs.proto", fileDescriptor_23033505e9d20bff) }

var fileDescriptor_23033505e9d20bff = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcb, 0x2f, 0xc9,
	0x4c, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x86, 0xf0, 0xc0, 0x1c, 0x25, 0x7f,
	0x2e, 0xf1, 0xe0, 0xd4, 0xbc, 0x14, 0x3f, 0x90, 0x50, 0x66, 0x72, 0x62, 0x49, 0x66, 0x7e, 0x9e,
	0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x0c, 0x17, 0x67, 0x58, 0x62, 0x72, 0x62, 0x5e,
	0x72, 0xa5, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x42, 0x40, 0x48, 0x8c, 0x8b,
	0x2d, 0x24, 0x31, 0xdd, 0xd3, 0xa5, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x33, 0x08, 0xca, 0x53,
	0x12, 0xe3, 0x62, 0x71, 0xca, 0xcf, 0xcf, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0xcf, 0x06, 0x6b, 0xe3,
	0x08, 0x62, 0xca, 0xcf, 0x36, 0x8a, 0xe0, 0x62, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15,
	0xf2, 0xe5, 0x12, 0x40, 0xb7, 0x53, 0x48, 0x45, 0x0f, 0xc9, 0x55, 0x7a, 0x38, 0x9c, 0x24, 0x25,
	0x88, 0xa2, 0x0a, 0x64, 0x8f, 0x12, 0x43, 0x12, 0x1b, 0x98, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0xd1, 0x12, 0x10, 0xe6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	SendNotification(ctx context.Context, in *SendNotificationMessage, opts ...grpc.CallOption) (*Bool, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SendNotification(ctx context.Context, in *SendNotificationMessage, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/notifsproto.Service/SendNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	SendNotification(context.Context, *SendNotificationMessage) (*Bool, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) SendNotification(ctx context.Context, req *SendNotificationMessage) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifsproto.Service/SendNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SendNotification(ctx, req.(*SendNotificationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notifsproto.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _Service_SendNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifs.proto",
}
