// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recommends.proto

package recomsproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTagIDsMessage struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Expires              string   `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagIDsMessage) Reset()         { *m = GetTagIDsMessage{} }
func (m *GetTagIDsMessage) String() string { return proto.CompactTextString(m) }
func (*GetTagIDsMessage) ProtoMessage()    {}
func (*GetTagIDsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c477ca0b0e7414, []int{0}
}

func (m *GetTagIDsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagIDsMessage.Unmarshal(m, b)
}
func (m *GetTagIDsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagIDsMessage.Marshal(b, m, deterministic)
}
func (m *GetTagIDsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagIDsMessage.Merge(m, src)
}
func (m *GetTagIDsMessage) XXX_Size() int {
	return xxx_messageInfo_GetTagIDsMessage.Size(m)
}
func (m *GetTagIDsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagIDsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagIDsMessage proto.InternalMessageInfo

func (m *GetTagIDsMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GetTagIDsMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetTagIDsMessage) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

type SetTagIDsMessage struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Expires              string   `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	IDs                  []string `protobuf:"bytes,4,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTagIDsMessage) Reset()         { *m = SetTagIDsMessage{} }
func (m *SetTagIDsMessage) String() string { return proto.CompactTextString(m) }
func (*SetTagIDsMessage) ProtoMessage()    {}
func (*SetTagIDsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c477ca0b0e7414, []int{1}
}

func (m *SetTagIDsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTagIDsMessage.Unmarshal(m, b)
}
func (m *SetTagIDsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTagIDsMessage.Marshal(b, m, deterministic)
}
func (m *SetTagIDsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTagIDsMessage.Merge(m, src)
}
func (m *SetTagIDsMessage) XXX_Size() int {
	return xxx_messageInfo_SetTagIDsMessage.Size(m)
}
func (m *SetTagIDsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTagIDsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetTagIDsMessage proto.InternalMessageInfo

func (m *SetTagIDsMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SetTagIDsMessage) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *SetTagIDsMessage) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

func (m *SetTagIDsMessage) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

type Bool struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c477ca0b0e7414, []int{2}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type IDsMessage struct {
	IDs                  []string `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDsMessage) Reset()         { *m = IDsMessage{} }
func (m *IDsMessage) String() string { return proto.CompactTextString(m) }
func (*IDsMessage) ProtoMessage()    {}
func (*IDsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_83c477ca0b0e7414, []int{3}
}

func (m *IDsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDsMessage.Unmarshal(m, b)
}
func (m *IDsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDsMessage.Marshal(b, m, deterministic)
}
func (m *IDsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDsMessage.Merge(m, src)
}
func (m *IDsMessage) XXX_Size() int {
	return xxx_messageInfo_IDsMessage.Size(m)
}
func (m *IDsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IDsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IDsMessage proto.InternalMessageInfo

func (m *IDsMessage) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTagIDsMessage)(nil), "recomsproto.GetTagIDsMessage")
	proto.RegisterType((*SetTagIDsMessage)(nil), "recomsproto.SetTagIDsMessage")
	proto.RegisterType((*Bool)(nil), "recomsproto.Bool")
	proto.RegisterType((*IDsMessage)(nil), "recomsproto.IDsMessage")
}

func init() { proto.RegisterFile("recommends.proto", fileDescriptor_83c477ca0b0e7414) }

var fileDescriptor_83c477ca0b0e7414 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xcf, 0x4a, 0x03, 0x41,
	0x0c, 0xc6, 0xdd, 0x3f, 0x58, 0x37, 0x82, 0xae, 0x39, 0xe8, 0x50, 0x50, 0xca, 0x9c, 0x7a, 0xda,
	0x83, 0x3e, 0x80, 0x20, 0xa3, 0xcb, 0x1c, 0x04, 0xd9, 0xd6, 0x07, 0xd8, 0xd6, 0xb0, 0x94, 0xb6,
	0xa6, 0x4c, 0x16, 0xf1, 0x51, 0x7d, 0x1c, 0xd9, 0xa0, 0xb5, 0x2d, 0xd4, 0x53, 0x6f, 0xc9, 0xf7,
	0x25, 0xbf, 0x84, 0x0f, 0xf2, 0x40, 0x53, 0x5e, 0x2e, 0xe9, 0xfd, 0x4d, 0x8a, 0x55, 0xe0, 0x96,
	0xf1, 0x54, 0x15, 0xd1, 0xc6, 0xbe, 0x40, 0x5e, 0x52, 0x3b, 0xae, 0x1b, 0xef, 0xe4, 0x99, 0x44,
	0xea, 0x86, 0xf0, 0x0c, 0x62, 0xef, 0x4c, 0x34, 0x88, 0x86, 0x59, 0x15, 0x7b, 0x87, 0x08, 0x69,
	0xe0, 0x05, 0x99, 0x58, 0x15, 0xad, 0xd1, 0x40, 0x8f, 0x3e, 0x57, 0xb3, 0x40, 0x62, 0x12, 0x95,
	0x7f, 0x5b, 0x3b, 0x81, 0x7c, 0x74, 0x50, 0x22, 0xe6, 0x90, 0x78, 0x27, 0x26, 0x1d, 0x24, 0xc3,
	0xac, 0xea, 0x4a, 0x7b, 0x09, 0xe9, 0x03, 0xf3, 0xa2, 0xe3, 0xf2, 0x5c, 0xb9, 0x27, 0x55, 0xcc,
	0x73, 0x7b, 0x03, 0xb0, 0x71, 0xf5, 0x67, 0x2f, 0x5a, 0xef, 0xdd, 0x7e, 0x45, 0xd0, 0x1b, 0x51,
	0xf8, 0x98, 0x4d, 0x09, 0xef, 0x21, 0x5b, 0xff, 0x89, 0xd7, 0xc5, 0x46, 0x28, 0xc5, 0xee, 0xff,
	0xfd, 0x8b, 0x2d, 0xbb, 0x3b, 0x6d, 0x8f, 0xf0, 0x11, 0xb2, 0x72, 0x0f, 0x60, 0x37, 0xd2, 0xfe,
	0xd5, 0x96, 0xfd, 0x67, 0x28, 0xe6, 0xbc, 0xa4, 0xf6, 0x55, 0x28, 0xc8, 0x13, 0x87, 0x71, 0xdd,
	0x08, 0xee, 0x9b, 0xfe, 0x07, 0x33, 0x39, 0x56, 0xed, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x86,
	0x79, 0xcd, 0xe3, 0xf0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	SetTagIDs(ctx context.Context, in *SetTagIDsMessage, opts ...grpc.CallOption) (*Bool, error)
	GetTagIDs(ctx context.Context, in *GetTagIDsMessage, opts ...grpc.CallOption) (*IDsMessage, error)
	GetUsersForTags(ctx context.Context, in *IDsMessage, opts ...grpc.CallOption) (*IDsMessage, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SetTagIDs(ctx context.Context, in *SetTagIDsMessage, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/recomsproto.Service/SetTagIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetTagIDs(ctx context.Context, in *GetTagIDsMessage, opts ...grpc.CallOption) (*IDsMessage, error) {
	out := new(IDsMessage)
	err := c.cc.Invoke(ctx, "/recomsproto.Service/GetTagIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetUsersForTags(ctx context.Context, in *IDsMessage, opts ...grpc.CallOption) (*IDsMessage, error) {
	out := new(IDsMessage)
	err := c.cc.Invoke(ctx, "/recomsproto.Service/GetUsersForTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	SetTagIDs(context.Context, *SetTagIDsMessage) (*Bool, error)
	GetTagIDs(context.Context, *GetTagIDsMessage) (*IDsMessage, error)
	GetUsersForTags(context.Context, *IDsMessage) (*IDsMessage, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) SetTagIDs(ctx context.Context, req *SetTagIDsMessage) (*Bool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTagIDs not implemented")
}
func (*UnimplementedServiceServer) GetTagIDs(ctx context.Context, req *GetTagIDsMessage) (*IDsMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagIDs not implemented")
}
func (*UnimplementedServiceServer) GetUsersForTags(ctx context.Context, req *IDsMessage) (*IDsMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersForTags not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_SetTagIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagIDsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetTagIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recomsproto.Service/SetTagIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetTagIDs(ctx, req.(*SetTagIDsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetTagIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagIDsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetTagIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recomsproto.Service/GetTagIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetTagIDs(ctx, req.(*GetTagIDsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetUsersForTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetUsersForTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recomsproto.Service/GetUsersForTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetUsersForTags(ctx, req.(*IDsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recomsproto.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTagIDs",
			Handler:    _Service_SetTagIDs_Handler,
		},
		{
			MethodName: "GetTagIDs",
			Handler:    _Service_GetTagIDs_Handler,
		},
		{
			MethodName: "GetUsersForTags",
			Handler:    _Service_GetUsersForTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommends.proto",
}
